version: "3.7"
services:
  lc74-elasticsearch:
    container_name: lc74-elasticsearch
    build:
      dockerfile: elasticsearch/Dockerfile
      context: .
    networks:
      - fs74dxp1
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-plugins:/usr/share/elasticsearch/plugins
  lc74-mysql:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: lc74-mysql
    networks:
      - fs74dxp1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: liferay
      MYSQL_PASSWORD: liferay
      MYSQL_DATABASE: lc74lportal
    volumes:
      - mysql:/var/lib/mysql
  lc74-liferay:
    image: liferay/dxp:2024.q2.3
    container_name: lc74-liferay
    depends_on:
      - lc74-mysql
    environment:
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY: 10
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES: 10
      LIFERAY_JVM_OPTS: "-Xms2560m -Xmx4096m"
    networks: 
      - fs74dxp1
    ports: 
      - 8080:8080
      - 127.0.0.1:11311:11311
    volumes:
      - ./liferay-74/mount:/mnt/liferay
      - liferay-tools:/opt/liferay/tools
      - liferay-data:/opt/liferay/data
      - liferay-osgi-configs:/opt/liferay/osgi/configs
      - liferay-osgi-marketplace:/opt/liferay/osgi/marketplace
      - liferay-osgi-modules:/opt/liferay/osgi/modules
      - liferay-osgi-war:/opt/liferay/osgi/war
  lc74-kibana:
    image: kibana:8.11.4
    container_name: lc74-kibana
    depends_on:
      - lc74-elasticsearch
    networks:
      - fs74dxp1
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
networks:
  fs74dxp1:
    name: fs74dxp1
volumes:
  elasticsearch-data:
  elasticsearch-plugins:
  liferay-data:
  liferay-tools:
  liferay-osgi-configs:
  liferay-osgi-marketplace:
  liferay-osgi-modules:
  liferay-osgi-war:
  mysql: